In [ ]:
#陣列運算
import numpy as np

a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [ ]:
#陣列運算
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

a + b

array([ 3,  7, 11, 15, 19])

In [17]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #查維度
arr.shape #形狀
arr.size #裡面元素的數量
arr.dtype #型別

dtype('int64')

In [19]:
np.random.rand()
np.random.rand(3, 4)

array([[0.35122923, 0.51709478, 0.16710073, 0.79061242],
       [0.88486672, 0.30154945, 0.42670657, 0.93759195],
       [0.74536165, 0.67333152, 0.40818593, 0.09769062]])

In [26]:
scores = np.random.randint(50, 101,size=[4,5])
scores

array([[97, 99, 58, 63, 84],
       [99, 58, 92, 69, 74],
       [91, 55, 96, 82, 77],
       [95, 77, 54, 60, 63]], dtype=int32)