In [2]:
import numpy as np
arr = np.arange(10) *10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
#索引
arr[1]

#slice切割
arr[:5] #前5個
arr[-5:] #後5個

array([50, 60, 70, 80, 90])

In [15]:
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 96,  89,  91,  85,  74],
       [ 77, 100,  89,  97,  57],
       [ 51,  62,  67,  93,  50],
       [ 53,  55,  82,  57,  71],
       [ 70,  77,  75,  61,  87],
       [ 88,  81,  58,  71,  88],
       [ 66,  73,  95,  78,  99],
       [ 77,  77,  57,  55,  78],
       [ 68,  77,  68,  99,  65],
       [ 92,  57,  80,  67,  67],
       [ 54,  62,  55,  77,  85],
       [ 59,  85,  53,  80,  70],
       [ 85,  80,  87,  85,  86],
       [ 63,  84,  74, 100,  84],
       [ 91,  81,  54,  65,  99],
       [ 77,  67,  83,  61,  88],
       [ 78,  73,  52,  50,  73],
       [ 87,  86,  84,  67,  68],
       [ 82,  61,  73, 100,  99],
       [ 92,  66,  83,  71,  62],
       [ 51,  84,  96,  71,  93],
       [ 93,  92,  60,  59,  97],
       [ 56, 100,  68,  68,  79],
       [ 79,  55,  58,  52,  80],
       [ 83,  86,  82,  59,  94],
       [ 82,  74,  66,  92,  81],
       [ 50,  50,  92,  60,  80],
       [ 98,  78,  90,  89,  71],
       [ 52,  81,  93,  67,  87],
       [ 86,  

In [20]:
#第一位學生的分數
scores[0] #(5,)一維
scores[0,:] #(5,)一維
scores[0:1,:] #(1,5)二維

array([[96, 89, 91, 85, 74]], dtype=int32)

In [25]:
#前5位學生分數
scores[:5]
#前5位學生前3個分數
scores[:5,:3]

array([[ 96,  89,  91],
       [ 77, 100,  89],
       [ 51,  62,  67],
       [ 53,  55,  82],
       [ 70,  77,  75]], dtype=int32)

In [27]:
scores[:,0] #第一科分數
scores[:,1] #第二科分數
scores[:,2] #第三科分數

array([91, 89, 67, 82, 75, 58, 95, 57, 68, 80, 55, 53, 87, 74, 54, 83, 52,
       84, 73, 83, 96, 60, 68, 58, 82, 66, 92, 90, 93, 64, 53, 71, 81, 82,
       92, 62, 95, 65, 69, 90, 91, 55, 74, 61, 66, 81, 64, 72, 89, 62],
      dtype=int32)

In [29]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2]+ scores[:,3]+ scores[:,4]
total

array([435, 420, 323, 318, 370, 386, 411, 344, 377, 363, 333, 347, 423,
       405, 390, 376, 326, 392, 415, 374, 395, 401, 371, 324, 404, 395,
       332, 426, 380, 387, 388, 416, 358, 433, 389, 391, 327, 330, 409,
       430, 364, 358, 399, 379, 367, 327, 342, 421, 394, 413], dtype=int32)

In [30]:
total / 5

array([87. , 84. , 64.6, 63.6, 74. , 77.2, 82.2, 68.8, 75.4, 72.6, 66.6,
       69.4, 84.6, 81. , 78. , 75.2, 65.2, 78.4, 83. , 74.8, 79. , 80.2,
       74.2, 64.8, 80.8, 79. , 66.4, 85.2, 76. , 77.4, 77.6, 83.2, 71.6,
       86.6, 77.8, 78.2, 65.4, 66. , 81.8, 86. , 72.8, 71.6, 79.8, 75.8,
       73.4, 65.4, 68.4, 84.2, 78.8, 82.6])

In [ ]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([87. , 84. , 64.6, 63.6, 74. , 77.2, 82.2, 68.8, 75.4, 72.6, 66.6,
       69.4, 84.6, 81. , 78. , 75.2, 65.2, 78.4, 83. , 74.8, 79. , 80.2,
       74.2, 64.8, 80.8, 79. , 66.4, 85.2, 76. , 77.4, 77.6, 83.2, 71.6,
       86.6, 77.8, 78.2, 65.4, 66. , 81.8, 86. , 72.8, 71.6, 79.8, 75.8,
       73.4, 65.4, 68.4, 84.2, 78.8, 82.6])

In [ ]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([87. , 84. , 64.6, 63.6, 74. , 77.2, 82.2, 68.8, 75.4, 72.6, 66.6,
       69.4, 84.6, 81. , 78. , 75.2, 65.2, 78.4, 83. , 74.8, 79. , 80.2,
       74.2, 64.8, 80.8, 79. , 66.4, 85.2, 76. , 77.4, 77.6, 83.2, 71.6,
       86.6, 77.8, 78.2, 65.4, 66. , 81.8, 86. , 72.8, 71.6, 79.8, 75.8,
       73.4, 65.4, 68.4, 84.2, 78.8, 82.6])